### ISSUE TITLE
As a user I want it to allow more than 8 accounts

### ISSUE THREAD

**Issue by ddarkeh1** [Joifage/CSGOSmuffSwitcher#1]
As a user i'd like for the tool to be able to handle more than 8 accounts

**Comment by doofage** [comment]
Try gentools, can handle many accounts and also takes advantage of multiple cpu cores

**Comment by Joifage** [comment]
I've discussed with my project manager and I think we have found a way to implement 9 accounts - stay tuned for major update.

**Comment by Joifage** [comment]
More than 8 accounts has been achieved
